FROM registry.access.redhat.com/ubi9/nodejs-18-minimal

WORKDIR /app

COPY package.json yarn.lock ./

RUN node --version

# Assume root for initial actions that require privileges
USER root

# Best practice for non-root users is to start the ID from 5000
RUN adduser -u 5000 devuser

# Install software, and provide necessary permissions for the non-root user
RUN chown -R devuser:devuser /app && \
    chmod -R 755 /app && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    microdnf install yarn -y && \
    microdnf clean all

# Assume non-root user for rest of the operations, including running the app
USER devuser

# Build the dependencies
RUN yarn && \
    yarn cache clean --force

COPY --chown=devuser:devuser . .

# RUN yarn prepare-renew-endpoint

CMD yarn start
