FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN node --version
RUN apk update
RUN apk add python3
RUN yarn install && yarn cache clean --force
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

# RUN yarn prepare-renew-endpoint

VOLUME [ "/app" ]

CMD ["yarn", "start"]