version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        volumes:
            -   ./src:/app/src
        ports:
            - "3000:3000"
        container_name: mvj-ui-public
